# -*- coding: utf-8 -*-
"""Conditional looping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ESukyS_sL6G--PeWTFJfYL5uW2Tkw2_
"""

list1=[12,-7,5,64,-14]
print("Positive numbers in",list1,"are: ")
  
#traversing
for i in list1:   
    # checking condition
    if i >= 0:
       print(i, end = " ")

list2=[12,14,-95,3]
print("Positive numbers in",list2,"are: ")
  
#traversing
for i in list2:   
    # checking condition
    if i >= 0:
       print(i, end = " ")